/* Generated By:JavaCC: Do not edit this line. WikiParserConstants.java */
package code.lucamarrocco.wiki.parser;

public interface WikiParserConstants {

  int EOF = 0;
  int NOT = 4;
  int BREAKLINE = 5;
  int TITLE = 6;
  int ITALIC = 7;
  int BOLD = 8;
  int BOLDITALIC = 9;
  int UNDERLINE = 10;
  int OLIOLI = 11;
  int OLI = 12;
  int ULIULI = 13;
  int ULI = 14;
  int LBRACKET = 15;
  int RBRACKET = 16;
  int WIKIWORD = 17;
  int HTTPSTRING = 18;
  int STRING = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"!\"",
    "<BREAKLINE>",
    "\"=\"",
    "\"\\\'\\\'\"",
    "\"\\\'\\\'\\\'\"",
    "\"\\\'\\\'\\\'\\\'\\\'\"",
    "\"_\"",
    "\"##\"",
    "\"#\"",
    "\"**\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "<WIKIWORD>",
    "<HTTPSTRING>",
    "<STRING>",
    "\"\\\'\"",
  };

}
